version: 2
updates:

    - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"


   - package-ecosystem: "npm"
    directory: "/pkg/http/rest/static/js/"
    schedule:
      interval: "daily"